# Generated by Django 5.2.5 on 2025-09-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('authority', models.CharField(help_text='e.g., Ministry of Education', max_length=255)),
                ('due_date', models.DateField()),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('attached_file', models.FileField(blank=True, help_text='A file upload for a copy of the submitted document', null=True, upload_to='filings/')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the school', max_length=255)),
                ('location', models.CharField(blank=True, help_text='The general location of the school', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='A unique ID for each student (e.g., CPB00002)', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('profile_photo', models.ImageField(blank=True, help_text="A file upload for the student's photo", null=True, upload_to='profile_photos/')),
                ('current_grade', models.CharField(help_text="The student's current grade or university year", max_length=50)),
                ('eep_enroll_date', models.DateField(help_text='The date the student enrolled in the program')),
                ('out_of_program_date', models.DateField(blank=True, help_text='The date the student left the program (can be blank)', null=True)),
                ('student_status', models.CharField(choices=[('Pending Qualification', 'Pending Qualification'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Pending Qualification', max_length=50)),
                ('sponsorship_status', models.CharField(choices=[('Sponsored', 'Sponsored'), ('Unsponsored', 'Unsponsored')], default='Unsponsored', max_length=50)),
                ('has_housing_sponsorship', models.BooleanField(default=False)),
                ('sponsor_name', models.CharField(blank=True, help_text="The name of the student's sponsor", max_length=255)),
                ('guardian_name', models.CharField(help_text='The name(s) of the parent or guardian', max_length=255)),
                ('guardian_contact_info', models.TextField(blank=True)),
                ('home_location', models.CharField(help_text='The home location or slum area of the student', max_length=255)),
                ('has_birth_certificate', models.BooleanField(default=False)),
                ('has_sponsorship_contract', models.BooleanField(default=False)),
                ('school', models.ForeignKey(blank=True, help_text='The school the student is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_follow_up', models.DateField()),
                ('location_of_follow_up', models.CharField(max_length=255)),
                ('health_status_notes', models.TextField(help_text="Notes on the student's health, social, and home life status")),
                ('risk_factors', models.TextField(blank=True, help_text='A text field for a checklist of specific risk factors')),
                ('parent_work_status', models.CharField(max_length=255)),
                ('hygiene_products_provided', models.BooleanField(default=False)),
                ('staff_notes', models.TextField(blank=True, help_text='A text field for staff notes, recommendations, and protection concerns')),
                ('completed_by', models.CharField(max_length=100)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_records', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_period', models.CharField(help_text='The period the report covers (e.g., "Q1 2025")', max_length=100)),
                ('grade_level', models.CharField(help_text="The student's grade level at the time of the report", max_length=50)),
                ('subjects_and_grades', models.TextField(help_text='A text field to list subjects and grades')),
                ('overall_average', models.FloatField(blank=True, help_text='The overall grade average for the period', null=True)),
                ('pass_fail_status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10)),
                ('teacher_comments', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_reports', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10)),
                ('category', models.CharField(help_text='e.g., School Fees, Hot Lunches, Gas', max_length=100)),
                ('student', models.ForeignKey(blank=True, help_text='An optional link to the student associated with this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student')),
            ],
        ),
    ]
